### ISSUE TITLE
Trouble with install - ArtemisPrometheusMetricsPluginServlet is not a javax.servlet.Servlet

### ISSUE THREAD

**Issue by MrDimly** [rh-messaging/artemis-prometheus-metrics-plugin#34] opened 2024-08-06 14:41 UTC
Hi

I have Artemis 2.36.0 in docker apache/activemq-artemis
Instruction hasn't parent tag for "metrics" in broker.xml, but i fround - inside "core"
Patch bootstrap.xml - it's ok

But when Artemis starting - i have error (bottom)
May be it is because i compile source with OpenJDK 11 and started Artemis in OpenJDK 21 ?

`2024-08-06 14:25:53,396 WARN  [org.eclipse.jetty.webapp.WebAppContext] Failed startup of context o.e.j.w.WebAppContext@789c3057{/metrics,file:///var/lib/artemis-instance/tmp/webapps/metrics.war/webapp/,UNAVAILABLE,@Connector-0}{/var/lib/artemis-instance/web/metrics.war}
javax.servlet.UnavailableException: Servlet class com.redhat.amq.broker.core.server.metrics.plugins.ArtemisPrometheusMetricsPluginServlet is not a javax.servlet.Servlet
        at org.eclipse.jetty.servlet.ServletHolder.checkServletType(ServletHolder.java:514) ~[jetty-servlet-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:386) ~[jetty-servlet-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$2(ServletHandler.java:724) ~[jetty-servlet-10.0.22.jar:10.0.22]
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:749) ~[jetty-servlet-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392) ~[jetty-servlet-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304) ~[jetty-webapp-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:901) ~[jetty-server-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306) ~[jetty-servlet-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532) [jetty-webapp-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) [jetty-util-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) [jetty-util-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121) [jetty-util-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) [jetty-server-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) [jetty-util-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) [jetty-util-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.server.Server.start(Server.java:470) [jetty-server-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) [jetty-util-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) [jetty-server-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.server.Server.doStart(Server.java:415) [jetty-server-10.0.22.jar:10.0.22]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) [jetty-util-10.0.22.jar:10.0.22]
        at org.apache.activemq.artemis.component.WebServerComponent.start(WebServerComponent.java:238) [artemis-web-2.36.0.jar:2.36.0]
        at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.addExternalComponent(ActiveMQServerImpl.java:1016) [artemis-server-2.36.0.jar:2.36.0]
        at org.apache.activemq.artemis.cli.commands.Run.execute(Run.java:145) [artemis-cli-2.36.0.jar:2.36.0]
        at org.apache.activemq.artemis.cli.Artemis.internalExecute(Artemis.java:221) [artemis-cli-2.36.0.jar:2.36.0]
        at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:167) [artemis-cli-2.36.0.jar:2.36.0]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.apache.activemq.artemis.boot.Artemis.execute(Artemis.java:152) [artemis-boot.jar:2.36.0]
        at org.apache.activemq.artemis.boot.Artemis.main(Artemis.java:64) [artemis-boot.jar:2.36.0]
`

**Comment by brusdev** [comment] 2024-08-06 20:35
This issue is a duplicate of #29, artemis-prometheus-metrics-plugin 3.x is for future ActiveMQArtemis versions. You can use artemis-prometheus-metrics-plugin 2.1.0 for ActiveMQArtemis 2.36.0.

**Closed by brusdev** 2024-08-06 20:35 UTC
